version: '3.7'
services:
  portainer:
    image: "portainer/portainer"
    environment:
      - TZ=Asia/Shanghai
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
    ports:
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
  filebrowser:
    image: "filebrowser/filebrowser"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "~/filebrowser/srv:/srv"
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
    ports:
      - "8090:8090"
    command: filebrowser/filebrowser:v1.11.0 --port 8090
  nginx:
    image: "nginx:1.16.0"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - "~/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "~/nginx/cache:/cache"
    ports:
      - "8000:8000"
      - "8001:8001"
    deploy:
      restart_policy:
        condition: any
        max_attempts: 3
volumes:
  portainer_data: